"""tables created

Revision ID: 0376cd558403
Revises: 
Create Date: 2024-05-30 11:48:07.595006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0376cd558403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aap_terminal',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Branch_Id', sa.String(length=50), nullable=False),
    sa.Column('Branch_Name', sa.String(length=50), nullable=False),
    sa.Column('Mobile_No', sa.String(length=50), nullable=False),
    sa.Column('Sequence_No', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('account_credit',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=True),
    sa.Column('Deposit_Mode', sa.String(length=50), nullable=True),
    sa.Column('Reason', sa.String(length=50), nullable=True),
    sa.Column('PreOrder_Receipt_No', sa.String(length=20), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=False),
    sa.Column('Remaining_Balance', sa.Float(), nullable=False),
    sa.Column('Branch_Id', sa.String(length=50), nullable=False),
    sa.Column('Merchant_Id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('book_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('customer_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('daily_log',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Sales_Type', sa.String(length=20), nullable=False),
    sa.Column('Sales_Code', sa.String(length=20), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Bill_No', sa.String(length=250), nullable=False),
    sa.Column('Customer_Type', sa.String(length=20), nullable=False),
    sa.Column('Bill_Value', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.Column('PreOrder_Receipt_No', sa.String(length=20), nullable=True),
    sa.Column('PreOrder_Customer_Name', sa.String(length=20), nullable=True),
    sa.Column('PreOrder_Receipt_Amount', sa.Float(), nullable=True),
    sa.Column('Pending_Balance', sa.Float(), nullable=False),
    sa.Column('Branch_Id', sa.String(length=50), nullable=False),
    sa.Column('Merchant_Id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_daily_log_Bill_No'), 'daily_log', ['Bill_No'], unique=True)
    op.create_table('day_info',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('deposit_mode',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('deposit_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('expense_fund',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Expense_Fund_Details', sa.String(length=300), nullable=False),
    sa.Column('Amount', sa.Float(), nullable=False),
    sa.Column('Balance', sa.Float(), nullable=False),
    sa.Column('Branch_Id', sa.String(length=50), nullable=False),
    sa.Column('Merchant_Id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('payment_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('preorder_book',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Receipt_No', sa.String(length=250), nullable=False),
    sa.Column('Customer_Name', sa.String(length=50), nullable=False),
    sa.Column('Phone_No', sa.String(length=20), nullable=False),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.Column('Payment_Type', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Customer_Type', sa.String(length=50), nullable=True),
    sa.Column('Branch_Id', sa.String(length=50), nullable=False),
    sa.Column('Merchant_Id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Receipt_No')
    )
    op.create_table('sales_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.Column('Code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('upi_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upi_type')
    op.drop_table('sales_type')
    op.drop_table('preorder_book')
    op.drop_table('payment_type')
    op.drop_table('expense_fund')
    op.drop_table('deposit_type')
    op.drop_table('deposit_mode')
    op.drop_table('day_info')
    op.drop_index(op.f('ix_daily_log_Bill_No'), table_name='daily_log')
    op.drop_table('daily_log')
    op.drop_table('customer_type')
    op.drop_table('book_type')
    op.drop_table('account_credit')
    op.drop_table('aap_terminal')
    # ### end Alembic commands ###
